language: node_js
node_js:
- '10'
- '11'
cache:
  directories:
  - node_modules
sudo: true
intsall: npm ci
dd:
- openssl aes-256-cbc -K $encrypted_028c92626f10_key -iv $encrypted_028c92626f10_iv
  -in id_rsa.enc -out F:\\txyun\\id_rsa -d
